/asr_sdm_hardware:
  uart_can:
    uart_port: "/dev/ttyS3"
    system_emergency_heartbeat_timeout: 0.5
    use_emergency_handling: true
    check_external_emergency_heartbeat: $(var check_external_emergency_heartbeat)
    enable_cmd_limit_filter: true
    filter_activated_count_threshold: 5
    filter_activated_velocity_threshold: 1.0
    external_emergency_stop_heartbeat_timeout: 0.0
    stop_hold_acceleration: -1.5
    emergency_acceleration: -2.4
    moderate_stop_service_acceleration: -1.5
    stop_check_duration: 1.0
    nominal:
      vel_lim: 25.0